services:
  bot:
    build: .
    container_name: 5k-discount-bot
    restart: unless-stopped
    command: python run.py
    env_file:
      - .env
    volumes:
      - ./cookies-5ka-ru.txt:/app/cookies-5ka-ru.txt
    stop_grace_period: 1m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
